import Tooltip from "@/components/Tooltip";
import { LIMITS } from "@/lib/chatLimits";
import type { Dict, Locale } from "@/lib/dictionaries";
import type { RefObject } from "react";
import { AssistantText, ThinkingDots } from "./AssistantText";

export type AssistantMessage = { id: number; role: "user" | "assistant"; content: string; animate?: boolean };

type Props = {
  copy: Dict["assistant"]; lang: Locale; open: boolean; messages: AssistantMessage[]; input: string; loading: boolean; error: string | null;
  rootRef: RefObject<HTMLDivElement | null>; panelRef: RefObject<HTMLDivElement | null>; launcherRef: RefObject<HTMLButtonElement | null>;
  iconChatRef: RefObject<SVGSVGElement | null>; iconCloseRef: RefObject<SVGSVGElement | null>; listRef: RefObject<HTMLDivElement | null>; inputRef: RefObject<HTMLTextAreaElement | null>;
  setOpen: (open: boolean | ((open: boolean) => boolean)) => void; setInput: (input: string) => void; send: (text: string) => Promise<void>;
  reset: () => void; scrollToEnd: () => void; onSubmit: (event: React.FormEvent) => void; onKeyDown: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void;
};

export function AssistantPanel({ copy: t, lang, open, messages, input, loading, error, rootRef, panelRef, launcherRef, iconChatRef, iconCloseRef, listRef, inputRef, setOpen, setInput, send, reset, scrollToEnd, onSubmit, onKeyDown }: Props) {
  const empty = messages.length === 0;
  const latest = messages[messages.length - 1];
  const announce = latest?.role === "assistant" ? latest.content : "";
  return <div ref={rootRef} className="fixed bottom-[max(1rem,env(safe-area-inset-bottom))] right-[max(1rem,env(safe-area-inset-right))] z-[60] print:hidden">
    <div ref={panelRef} role="dialog" aria-label={t.title} style={{ opacity: 0, visibility: "hidden" }} className="absolute bottom-16 right-0 flex h-[min(560px,calc(100vh-9rem))] w-[min(380px,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-[20px] border border-white/[0.09] bg-[rgba(10,14,22,0.94)] shadow-[0_30px_90px_-24px_rgba(0,0,0,0.85)] backdrop-blur-2xl">
      <span aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-px" style={{ background: "linear-gradient(90deg, transparent, var(--brand-teal-bright), transparent)", opacity: 0.7 }} />
      <div data-stagger className="flex items-center justify-between gap-3 border-b border-white/[0.07] px-4 py-3.5">
        <div className="min-w-0"><div className="flex items-center gap-2 text-[10px] font-medium tracking-[0.24em] text-[var(--brand-teal-bright)] uppercase"><span className="relative flex h-1.5 w-1.5"><span aria-hidden className="absolute inline-flex h-full w-full rounded-full bg-[var(--brand-teal-bright)]" style={{ animation: "pulseDot 1.6s ease-in-out infinite" }} /><span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-[var(--brand-teal-bright)]" /></span>{t.eyebrow}</div><h2 className="mt-1 truncate text-[15px] leading-tight font-medium tracking-[-0.01em] text-white">{t.title}</h2></div>
        <div className="flex flex-none items-center gap-0.5">{!empty && <Tooltip label={t.reset} side="bottom"><button type="button" onClick={reset} aria-label={t.reset} className="grid h-8 w-8 place-items-center rounded-lg text-white/55 transition-colors hover:bg-white/[0.06] hover:text-white"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden><path d="M3 12a9 9 0 1 0 3-6.7L3 8" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /><path d="M3 3.5V8h4.5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg></button></Tooltip>}<Tooltip label={t.close} side="bottom"><button type="button" onClick={() => setOpen(false)} aria-label={t.close} className="grid h-8 w-8 place-items-center rounded-lg text-white/55 transition-colors hover:bg-white/[0.06] hover:text-white"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" /></svg></button></Tooltip></div>
      </div>
      <div ref={listRef} aria-busy={loading} className="no-scrollbar flex-1 space-y-3.5 overflow-y-auto overscroll-contain px-4 py-4">
        {empty ? <div data-stagger className="space-y-4"><p className="text-[14px] leading-relaxed text-white/80">{t.greeting}</p><ul className="flex flex-col gap-2">{t.suggestions.map((suggestion) => <li key={suggestion}><button type="button" onClick={() => void send(suggestion)} className="group flex w-full items-center gap-2.5 rounded-xl border border-white/[0.09] bg-white/[0.02] px-3 py-2.5 text-left transition-colors hover:border-[var(--brand-teal)]/40 hover:bg-white/[0.05]"><span className="mono text-[12px] leading-none text-[var(--brand-teal-bright)] transition-transform group-hover:translate-x-0.5">→</span><span className="text-[13.5px] leading-snug text-white/75 group-hover:text-white">{suggestion}</span></button></li>)}</ul></div> : messages.map((message) => message.role === "user" ? <div key={message.id} className="flex justify-end"><div className="max-w-[85%] rounded-2xl rounded-br-md bg-white/[0.08] px-3.5 py-2.5 text-[14px] leading-relaxed whitespace-pre-wrap break-words text-white">{message.content}</div></div> : <div key={message.id} className="flex justify-start gap-2.5"><span aria-hidden className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-[var(--brand-red)]" style={{ boxShadow: "0 0 6px rgba(214,59,59,0.8)" }} /><div className="max-w-[88%] text-[14px] leading-relaxed whitespace-pre-wrap break-words text-white/85"><AssistantText text={message.content} animate={!!message.animate} onTick={scrollToEnd} /></div></div>)}
        {loading && <div className="flex justify-start gap-2.5" role="status"><span className="sr-only">{t.thinking}</span><span aria-hidden className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-[var(--brand-red)]" style={{ boxShadow: "0 0 6px rgba(214,59,59,0.8)" }} /><ThinkingDots /></div>}{error && <p role="alert" className="text-[13px] leading-snug text-[#f3867f]">{error}</p>}
      </div>
      <p className="sr-only" aria-live="polite" aria-atomic="true">{announce}</p>
      <form onSubmit={onSubmit} data-stagger className="border-t border-white/[0.07] p-3"><div className="flex items-center gap-2 rounded-xl border border-white/[0.1] bg-white/[0.03] px-3 py-2 transition-colors focus-within:border-[var(--brand-teal)]/50"><textarea ref={inputRef} rows={1} value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={onKeyDown} placeholder={t.placeholder} aria-label={t.title} maxLength={LIMITS.maxCharsPerMessage} className="no-scrollbar max-h-28 flex-1 resize-none bg-transparent text-[14px] leading-relaxed text-white placeholder:text-white/45 outline-none" /><button type="submit" disabled={!input.trim() || loading} aria-label={t.send} className="grid h-8.5 w-8.5 flex-none place-items-center rounded-lg bg-[var(--brand-red)] text-white transition-colors hover:bg-[var(--brand-red-deep)] disabled:cursor-not-allowed disabled:opacity-35" style={{ boxShadow: "0 1px 4px rgba(214,59,59,0.25)" }}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden><path d="M4 12h15M13 6l6 6-6 6" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" /></svg></button></div><p className="mono mt-2 px-1 text-[9.5px] tracking-[0.14em] text-white/55 uppercase">{t.tag}</p><p className="mt-1.5 px-1 text-[11px] leading-snug text-white/45">{t.disclaimer}{" "}<a href={`/${lang}/privacy`} className="underline decoration-white/30 underline-offset-2 transition-colors hover:text-white/80">{t.privacyLink}</a></p></form>
    </div>
    <Tooltip label={open ? t.close : t.launch} side="left"><button ref={launcherRef} type="button" onClick={() => setOpen((value) => !value)} aria-label={open ? t.close : t.launch} aria-expanded={open} style={{ opacity: 0 }} className="relative grid h-12 w-12 place-items-center rounded-full bg-[var(--brand-red)] text-white transition-colors hover:bg-[var(--brand-red-deep)]"><span aria-hidden className="pointer-events-none absolute inset-0 rounded-full" style={{ boxShadow: "0 3px 10px -2px rgba(214,59,59,0.35)" }} /><svg ref={iconChatRef} width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden className="absolute"><path d="M4 5.5h16a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H9l-4 3.5V16.5H4a1 1 0 0 1-1-1v-9a1 1 0 0 1 1-1Z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round" /><path d="M7.5 10h9M7.5 13h6" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" /></svg><svg ref={iconCloseRef} width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden className="absolute" style={{ opacity: 0 }}><path d="M6 9l6 6 6-6" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" /></svg></button></Tooltip>
  </div>;
}
